# Generated by Django 4.1.2 on 2022-10-13 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auto', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Managment',
            fields=[
                ('id', models.PositiveSmallIntegerField(primary_key=True, serialize=False, verbose_name='ID Auto')),
                ('km', models.PositiveSmallIntegerField(default=0, verbose_name='Kilometraje')),
                ('descripcion', models.CharField(max_length=1000, verbose_name='Dirección')),
                ('costo', models.IntegerField(default=0, verbose_name='Costo')),
                ('fecha', models.DateField(verbose_name='Fecha de mantenimiento')),
                ('auto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auto.auto')),
            ],
            options={
                'verbose_name': 'Mantenimiento',
                'verbose_name_plural': 'Mantenimientos',
            },
        ),
    ]
